version: '3'

services:
   redis:
      image: redis:latest
      ports: 
         - 6333:6379
      volumes:
         - ./config/redis.conf:/redis.conf
      command: ["redis-server", "/redis.conf"]
